version: "3.8"
services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: book
      MYSQL_DATABASE: library
  JJDZR11-Konstruktorsi:
    image: library:0.1
    depends_on:
      - mysql
    ports:
      - 8080:8080