version: "3.8"
services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: kamil
    volumes:
      - ./mysql:/var/lib/mysql
  JJDZR11-Konstruktorsi:
    image: library
    depends_on:
      - mysql
    ports:
      - 8080:8080